data_path:
  - data/data/Rice_Image_Dataset
  - data/data_refined/RiceRefined-v2
labels2id_meta: data/labels_metainfo/labels2id_metainfo.json
id2labels_meta: data/labels_metainfo/id2labels_metainfo.json
